### ISSUE TITLE
Allow per-task configuration of gbasf2 release

### ISSUE THREAD

**Issue by philiptgrace** [nils-braun/b2luigi#42]
I have a particular use-case for this feature request: I would like to use release-05 for generating ntuples (to access newly introduced variables), but the FEI skimming of signal samples must be done with release-04 (since FEI performance changed significantly with the redefinition of some angular variables between releases, and it needs to be retrained).

This would not be a large change. I'm picturing a task definition like the following:
```python
class GridFEISkim(Basf2PathTask):
    batch_system = "gbasf2"
    gbasf2_download_dataset = False
    gbasf2_release = "release-04-02-08"
```
where  `_build_gbasf2_submit_command` checks for the attribute `gbasf2_release`. However, this would mean that `gbasf2_release` exists as both a setting and an attribute, which is maybe not ideal.

**Comment by FelixMetzner** [comment]
You might want to have a look at [the respective section of the `b2luigi` documentation](https://b2luigi.readthedocs.io/en/stable/documentation/api.html#b2luigi.get_setting). You can overwrite a setting by defining a attribute with the same name in the task. So this is exactly how it is intended to be done. Or maybe I misunderstood the question.

From an analyst's point of view, I would say that it is not best practices to do different parts of the same analysis with different releases. But this is not the place to discuss this.

**Comment by meliache** [comment]
Your code example above should already perfectly work. The `gbasf2_release` setting already exists and is also documented in the [gbasf2 section](https://b2luigi.readthedocs.io/en/stable/usage/batch.html#gbasf2-wrapper-for-lcg) of the internal documentation.

You're mentioning the internal function `_build_gbasf2_submit_command`, so I guess you actually looked at the code? If yes that's good. There's the following line ([source](https://github.com/nils-braun/b2luigi/blob/8f7160e64190a7ba25db189c9ab4b98a479db7ca/b2luigi/batch/processes/gbasf2.py#L399)):

```python
gbasf2_release = get_setting("gbasf2_release", default=get_basf2_git_hash(), task=self.task)
```
Only the default is to your the release from your environment which is given by `get_basf2_git_hash()`, but if a setting is given it uses the setting. And it also checks the current tasks for settings, which is why I had to add the `task=self.task`.

I didn't put all the settings into the example file, because it would have made them too verbose. From a UX point of view I don't really think it is suboptimal how the gbasf2 wrapper for b2luigi is configured through settings, because these settings lack discoverability. You can't just tab-complete the settings or use your IDE to find valid settings, the only way to find them is know where to look in the code or (easier) read the documentation.

If you have any better ways how to configure gbasf2 from luigi, feel free to do a PR. Also I'm always super happy if you have suggestions how to improve the documentation or the user examples.

**Comment by philiptgrace** [comment]
Thank you both for your responses. I had misunderstood that `get_setting` _does_ check for settings via task attributes, and that this is intended behaviour.
