### ISSUE TITLE
Allow dash in gbasf2 project names 

### ISSUE THREAD

**Issue by Bilokin** [nils-braun/b2luigi#44]
Hello @meliache,

thanks a lot for the gbasf2 implementation in b2luigi, it is incredibly useful to us!
I have a small feature request: To allow "-" symbol in gbasf2 project names, that are submitted by b2luigi. 
It is an allowed symbol for BelleDIRAC and it would increase readability of project names. 

Also it would be nice to have _an option_ to not to add random string at the end of project name, but leave project name entirely up to user. The motivation is that the project names in BelleDIRAC can be only up to 32 symbols in length, and if the limit is exceeded, the project name is just truncated without any notification.

**Comment by meliache** [comment]
Hi,


## 1. `-` in project names

I read the 
[gbasf2 confluence
documentation](https://confluence.desy.de/display/BI/Computing+GBasf2#ComputingGBasf2-Project)
for what is allowed in gbasf2 project names and it states:

> - The length of a project name must be less than or equal to 32 characters that consists of alphanumerics ([a-zA-Z0-9]).
>   - Allowed characters are alphanumerics ([a-zA-Z0-9]) to avoid unexpected side effect on file system or database.
>   - '.' should be avoided because it prevents registration of output to the metadata catalog, leading to job failures even when your jobs can be completed to run. See GBasf2 Troubleshooting.
>   - '-' and '_' seem to work in standard use cases, though not guaranteed
>     against every aspect.

I wanted to check the project name from within my wrapper before creating the
gbasf2 submit command, so that I can provide the user with a more helpful error
message. I wanted to only support what's "officially" allowed and that are
alphanumerics and not allow characters that might or might not work, because if
something brakes in the future, the users of the wrapper will of course ask me
for support. But if you are sure that there's no problems with that, I could
allow dashes and underscores and maybe print a warning/info message.


## 2. Option to disable the project name hash suffixes

I am aware of the 32 character limit for project names. If the user-provided
project-name-prefix is therefore longer than 22 characters (the hash is 10
characters), then b2luigi will raise an error with a message explaining the
limit. So in theory, it will either run or raise an error, nothing is truncated
without notification. So I don't really understand your motivation, maybe you
can explain it better. If you want to have the ability to have longer project
names, I can understand it, maybe I could also add a setting to shorten the
arbitrary length of 10 for the hash down to e.g. 5 or maybe even add a setting
to set it to an arbitrary length. Then, you could just set it to 0, but that
could result in problems if the user doesn't ensure their project name is unique
for each combination of parameters. After all, it is there for a reason.

The "random" strings are deterministically generated by hashing the unique task
ID, which in turn is generated from the task name and the values of its luigi
parameters (in that sense it is pseudo-random). It not being totally random
means that if you re-run the same steering file, the project name suffix will
not change and thus it will notice that a project with the same name already
exists on the grid and not re-submit it, but instead download the output of the
existing project (if it hasn't been downloaded yet). However, if any of the task
parameters changes, for example if you have the value of a cut as a luigi
parameter and change that, then the "random string" will change and b2luigi will
happily submit a new project. This string is a way to make sure that the project
running on the grid is actually derived from the currently running task and
wasn't created by some other task, where the user just forgot to change the
project name when copy-pasting.

**Comment by meliache** [comment]
To allow the dashes with a warning I opened the PR https://github.com/nils-braun/b2luigi/pull/45

**Comment by Bilokin** [comment]
Thanks for the PR.
From my personal experience, I never had any problems with the '-' symbol in project names. 
Also I asked responsible for user analysis in Computing Group, and he told me that '-' and '_' will be supported in the future, so there is no need to worry. And, probably, there is no need for warnings too

**Comment by meliache** [comment]
Thanks for figuring that out. I removed the warning from the PR, removing code is always good. It's a bit of a problem of the gbasf2 documentation living on confluence instead of being in-code documentation like sphinx, so I never now if something written there is up-to-date...

I don't know how important the option to disable the automatic uniquification of gbasf2 project names via this task_id hash string is. I could do it, but to me this seems that if we want that, we should create a separate issue, since this issue is called _"Allow dash in gbasf2 project names"_ and that is already solved, at least once the PR will be merged.

**Comment by nils-braun** [comment]
Done
