### ISSUE TITLE
Proposal: add Michael as the main developer on readthedocs

### ISSUE THREAD

**Issue by nils-braun** [nils-braun/b2luigi#53]
As @meliache is now doing the main project work, he should also be added (or even replace me) on the main documentation page (https://b2luigi.readthedocs.io/en/stable/#the-team).

**Comment by meliache** [comment]
Thanks for nominating me, it's fine with me if others agree.

Potential counter-arguments would be that I haven't worked much on the core of the package yet and I think you still understand the core of the code better than me. Most of my work had been on the gbasf2 wrapper that I implemented. But I guess I'll still be able to ask for your opinion on PRs even if it might take a while with you having a full-time job.

I don't think I will divert much more time to b2luigi, since I am trying to focus my efforts on my PhD topic for my last year. But I guess this is not what you had been asking for. At least, I have more contact to the user-base than you have.

Cheers
Michael
